# This program demonstrates how to control DC motors connected
# to a motor driver.
# The PWM signal to the motor driver is generated by the GPIO pins. 


# General libraries
import time
# Libraries for the GPIO pins
from gpiozero import OutputDevice, Button


# Set GPIO Pins (uses BCM numbering)
# We are only using one of the motors and one of the GPIO_Aencoders in this example 
GPIO_Ain1 = OutputDevice(17)
GPIO_Ain2 = OutputDevice(27)
AencoderPin = 20
GPIO_Aencoder = Button(AencoderPin, pull_up=False)


# The PWM pin is set permanently to HIGH; this sets the motor speed to the maximum value
# If we want to change the motor speed, we need to attach a PWM signal to the pin
# (see motor example)
GPIO_Apwm = OutputDevice(12)
GPIO_Apwm.on()

# Motor is stopped 
GPIO_Ain1.off()
GPIO_Ain2.off()

encoderTicksA = 0
encoderTargetA = -1
encoderTargetAReached = False

# Execute this function when there is an event on the GPIO_Aencoder pin (i.e., a transition)
def encoderCountA(channel):
    global encoderTicksA
    global encoderTargetA
    global encoderTargetAReached

    # If this is an event on the AGPIO_Aencoder pin
    if (channel == AencoderPin):
        encoderTicksA = encoderTicksA + 1                                           # Increase the tick count
        if (encoderTargetA > 0) and (encoderTicksA >= encoderTargetA):              # If we reached the target count, stop the motors and reset the count
            encoderTargetAReached = True
        else:
            encoderTargetAReached = False
    #print(encoderTicksA)

# Add an event to the GPIO_Aencoder pin
GPIO_Aencoder.when_pressed = encoderCountA

# Initialize the finite state machine
FSM1State = 0
FSM1NextState = 0
FSM1LastTime = 0


try:
    print("Press CTRL+C to end the program.")
        
    while True:

        # Check the current time
        currentTime = time.time()

        # Update the state
        FSM1State = FSM1NextState

        # Check the state transitions for FSM 1
        # State 0: Start the motor going forward and set up the GPIO_Aencoder
        if (FSM1State == 0):
            encoderTargetA = 39                             # Set the target for how much we want the motors to move
            encoderTicksA = 0                               # Reset the number of ticks thus far
            encoderTargetAReached = False
            GPIO_Ain1.on()
            GPIO_Ain2.off()
            maxTime = 1000
            print ("Forward")
            FSM1NextState = 1

        # State 1: Wait for max time or when GPIO_Aencoder stops (by the GPIO_Aencoder callback routine)
        elif (FSM1State == 1):
            if (currentTime - FSM1LastTime > maxTime):
                print("Motor A stopped because the time limit was reached")
                GPIO_Ain1.off()
                GPIO_Ain2.off()
                encoderTargetA = -1                         # Ignore GPIO_Aencoder from now on
                FSM1NextState = 2
            elif (encoderTargetAReached == True):
                print("Motor A stopped - GPIO_Aencoder target reached" )
                GPIO_Ain1.off()
                GPIO_Ain2.off()
                encoderTargetA = -1                         # Ignore GPIO_Aencoder from now on
                FSM1NextState = 2
            else:
                FSM1NextState = 1

        # State 2: Wait
        elif (FSM1State == 2):
            if (currentTime - FSM1LastTime > 1):
                FSM1NextState = 3
            else:
                FSM1NextState = 2

        # State 3: Start the motor going forward and set up the GPIO_Aencoder
        elif (FSM1State == 3):
            encoderTargetA = 45                             # Set the target for how much we want the motors to move
            encoderTicksA = 0                               # Reset the number of ticks thus far
            encoderTargetAReached = False
            GPIO_Ain1.off()
            GPIO_Ain2.on()
            maxTime = 1000
            print ("Backward")
            FSM1NextState = 4

        # State 4: Wait for max time or when GPIO_Aencoder stops (by the GPIO_Aencoder callback routine)
        elif (FSM1State == 4):
            if (currentTime - FSM1LastTime > maxTime):
                print("Motor A stopped because the time limit was reached")
                GPIO_Ain1.off()
                GPIO_Ain2.off()
                encoderTargetA = -1                         # Ignore GPIO_Aencoder from now on
                FSM1NextState = 5
            elif (GPIO_AencoderTargetAReached == True):
                print("Motor A stopped - GPIO_Aencoder target reached" )
                GPIO_Ain1.off()
                GPIO_Ain2.off()
                encoderTargetA = -1                         # Ignore GPIO_Aencoder from now on
                FSM1NextState = 5
            else:
                FSM1NextState = 4

        # State 5: Wait
        elif (FSM1State == 5):
            if (currentTime - FSM1LastTime > 1):
                FSM1NextState = 0
            else:
                FSM1NextState = 5

        # State ??
        else:
            print("Error: unrecognized state for FSM1: "+str(FSM1State))
            break   

        # If there is a state change, record the time    
        if (FSM1State != FSM1NextState):
            FSM1LastTime = currentTime



# Quit the program when the user presses CTRL + C
except KeyboardInterrupt:
    pass    
finally:
    # Stop the motor
    GPIO_Ain1.off()
    GPIO_Ain2.off()
    GPIO_Aencoder.close()
    # Clean up the resources



