# This program demonstrates how to control DC motors connected
# to a motor driver.
# The PWM signal to the motor driver is generated by the GPIO pins. 


# General libraries
import time
# Libraries for the GPIO pins
import RPi.GPIO as GPIO

 
# GPIO Mode (BOARD / BCM)
GPIO.setmode(GPIO.BCM)
 
# Set GPIO Pins
GPIO_Ain1 = 17
GPIO_Ain2 = 27
GPIO_Apwm = 22
GPIO_Bin1 = 5
GPIO_Bin2 = 6
GPIO_Bpwm = 13

# Set GPIO direction (IN / OUT)
GPIO.setup(GPIO_Ain1, GPIO.OUT)
GPIO.setup(GPIO_Ain2, GPIO.OUT)
GPIO.setup(GPIO_Apwm, GPIO.OUT)
GPIO.setup(GPIO_Bin1, GPIO.OUT)
GPIO.setup(GPIO_Bin2, GPIO.OUT)
GPIO.setup(GPIO_Bpwm, GPIO.OUT)


# Set the pwm frequency
pwm_frequency = 1000

# Create PWM instances
pwmA = GPIO.PWM(GPIO_Apwm, pwm_frequency)
pwmB = GPIO.PWM(GPIO_Bpwm, pwm_frequency)


# Both motors are stopped 
GPIO.output(GPIO_Ain1, False)
GPIO.output(GPIO_Ain2, False)
GPIO.output(GPIO_Bin1, False)
GPIO.output(GPIO_Bin2, False)

# Set the duty cycle (between 0 and 100)
# The duty cycle determines the speed of the wheels
# We start with a duty cycle of 100
pwmA.start(100)
pwmB.start(100)


# Initialize the finite state machine
FSM1State = 0
FSM1NextState = 0
FSM1LastTime = 0


try:
    print("Press CTRL+C to end the program.")
        
    while True:

        # Check the current time
        currentTime = time.time()

        # Update the state
        FSM1State = FSM1NextState


        # Check the state transitions for FSM 1
        if (FSM1State == 0):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, True)
                GPIO.output(GPIO_Ain2, False)
                GPIO.output(GPIO_Bin1, True)
                GPIO.output(GPIO_Bin2, False)
                pwmA.ChangeDutyCycle(50)         
                pwmB.ChangeDutyCycle(50)      
                print ("Forward half speed")
                FSM1NextState = 1
            else:
                FSM1NextState = 0

        elif (FSM1State == 1):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, True)
                GPIO.output(GPIO_Ain2, False)
                GPIO.output(GPIO_Bin1, True)
                GPIO.output(GPIO_Bin2, False)
                pwmA.ChangeDutyCycle(100)
                pwmB.ChangeDutyCycle(100)
                print ("Forward full speed")
                FSM1NextState = 2
            else:
                FSM1NextState = 1

        elif (FSM1State == 2):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, False)
                GPIO.output(GPIO_Ain2, True)
                GPIO.output(GPIO_Bin1, False)
                GPIO.output(GPIO_Bin2, True)
                pwmA.ChangeDutyCycle(33)
                pwmB.ChangeDutyCycle(33)
                print ("Backward third speed")
                FSM1NextState = 3
            else:
                FSM1NextState = 2

        elif (FSM1State == 3):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, False)
                GPIO.output(GPIO_Ain2, False)
                GPIO.output(GPIO_Bin1, False)
                GPIO.output(GPIO_Bin2, False)
                print ("Stop")     
                FSM1NextState = 0
            else:
                FSM1NextState = 3

        else:
            print("Error: unrecognized state for FSM1")
            break   

        # If there is a state change, record the time    
        if (FSM1State != FSM1NextState):
            FSM1LastTime = currentTime
                
                                
            
# Quit the program when the user presses CTRL + C
except KeyboardInterrupt:
    pass    
finally:
    # Stop the motors
    GPIO.output(GPIO_Ain1, False)
    GPIO.output(GPIO_Ain2, False)
    GPIO.output(GPIO_Bin1, False)
    GPIO.output(GPIO_Bin2, False)
    # Clean up the resources
    GPIO.cleanup()
