# This program demonstrates how to control DC motors connected
# to a motor driver.
# The PWM signal to the motor driver is generated by the
# PCA9685 PWM driver.


# General libraries
import time
# Libraries for the GPIO pins
import RPi.GPIO as GPIO
# Libraries for the PWM driver with motors
from adafruit_pca9685 import PCA9685
import busio
import board

 
# GPIO Mode (BOARD / BCM)
GPIO.setmode(GPIO.BCM)
 
# set GPIO Pins
GPIO_Ain1 = 17
GPIO_Ain2 = 27
GPIO_Bin1 = 5
GPIO_Bin2 = 6

# Set GPIO direction (IN / OUT)
GPIO.setup(GPIO_Ain1, GPIO.OUT)
GPIO.setup(GPIO_Ain2, GPIO.OUT)
GPIO.setup(GPIO_Bin1, GPIO.OUT)
GPIO.setup(GPIO_Bin2, GPIO.OUT)

# Specify the channels you are using on the PWM driver
channel_motor1 = 4
channel_motor2 = 5


# Set the pwm frequency
# However, if we are using ServoKit (for servos),
# this will automatically be overwritten to 50.
pwm_frequency = 1000

# Configure the PWM driver for the motors
i2c = busio.I2C(board.SCL, board.SDA)
pca = PCA9685(i2c)

# Initialize the PWM driver for the motors 
motor_pwmA = pca.channels[channel_motor1]
motor_pwmB = pca.channels[channel_motor2]
pca.frequency = pwm_frequency

# Helper function
def duty(speed):
    return int(speed * 65535)

# Both motors are stopped 
GPIO.output(GPIO_Ain1, False)
GPIO.output(GPIO_Ain2, False)
GPIO.output(GPIO_Bin1, False)
GPIO.output(GPIO_Bin2, False)

# Set the initial speed of the motors
speed = 0.5
motor_pwmA.duty_cycle = duty(speed)
motor_pwmB.duty_cycle = duty(speed)


# Initialize the finite state machine
FSM1State = 0
FSM1NextState = 0
FSM1LastTime = 0


try:
    print("Press CTRL+C to end the program.")
        
    while True:

        # Check the current time
        currentTime = time.time()

        # Update the state
        FSM1State = FSM1NextState


        # Check the state transitions for FSM 1
        if (FSM1State == 0):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, True)
                GPIO.output(GPIO_Ain2, False)
                GPIO.output(GPIO_Bin1, True)
                GPIO.output(GPIO_Bin2, False)
                speed = 0.5
                motor_pwmA.duty_cycle = duty(speed)
                print ("Forward half speed")
                FSM1NextState = 1
            else:
                FSM1NextState = 0

        elif (FSM1State == 1):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, True)
                GPIO.output(GPIO_Ain2, False)
                GPIO.output(GPIO_Bin1, True)
                GPIO.output(GPIO_Bin2, False)
                speed = 1.0
                motor_pwmA.duty_cycle = duty(speed)
                print ("Forward full speed")
                FSM1NextState = 2
            else:
                FSM1NextState = 1

        elif (FSM1State == 2):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, False)
                GPIO.output(GPIO_Ain2, True)
                GPIO.output(GPIO_Bin1, False)
                GPIO.output(GPIO_Bin2, True)
                speed = 0.33
                motor_pwmA.duty_cycle = duty(speed)
                print ("Backward third speed")
                FSM1NextState = 3
            else:
                FSM1NextState = 2

        elif (FSM1State == 3):
            if (currentTime - FSM1LastTime > 1):
                GPIO.output(GPIO_Ain1, False)
                GPIO.output(GPIO_Ain2, False)
                GPIO.output(GPIO_Bin1, False)
                GPIO.output(GPIO_Bin2, False)
                print ("Stop")
                FSM1NextState = 0
            else:
                FSM1NextState = 3

        else:
            print("Error: unrecognized state for FSM1")
            break   

        # If there is a state change, record the time    
        if (FSM1State != FSM1NextState):
            FSM1LastTime = currentTime
                

            
# Quit the program when the user presses CTRL + C
except KeyboardInterrupt:
    pass    
finally:
    # Stop the motors
    GPIO.output(GPIO_Ain1, False)
    GPIO.output(GPIO_Ain2, False)
    GPIO.output(GPIO_Bin1, False)
    GPIO.output(GPIO_Bin2, False)
    # Clean up the resources
    GPIO.cleanup()

