# This program demonstrates how to control DC motors connected
# to a motor driver.
# The PWM signal to the motor driver is generated by the GPIO pins.
# This shows the basic setup without a finite state machine.


# General libraries
import time
# Libraries for the GPIO pins
from gpiozero import OutputDevice
# Libraries for the harware PWM
import pigpio


# Set GPIO Pins (uses BCM numbering)
GPIO_Ain1 = OutputDevice(17)
GPIO_Ain2 = OutputDevice(27)
GPIO_Bin1 = OutputDevice(5)
GPIO_Bin2 = OutputDevice(6)

# Set GPIO pins for harware PWM
# Note: There are only two hardware PWMs
#         channel 0: pin 12 (but it may make 18 unusable as well)
#         channel 1: pin 19 (but it may make 13 unusable as well)
GPIO_Apwm = 12
GPIO_Bpwm = 19


# Set the pwm frequency
pwm_frequency = 1000

# Start the hardware pwm service
pi = pigpio.pi()

# Helper function
def dutyHWpwm(speed):
    if not 0 <= speed <= 1:
        raise ValueError("Speed must be between 0 and 1")
    return int(speed * 1000000)


# Both motors are stopped 
GPIO_Ain1.off()
GPIO_Ain2.off()
GPIO_Bin1.off()
GPIO_Bin2.off()

# Set the initial speed of the motors
speed = 0.5
pi.hardware_PWM(GPIO_Apwm, pwm_frequency, dutyHWpwm(speed))
pi.hardware_PWM(GPIO_Bpwm, pwm_frequency, dutyHWpwm(speed))

 
try:
    print("Press CTRL+C to end the program.")
        
    while True:

        GPIO_Ain1.on()
        GPIO_Ain2.off()
        GPIO_Bin1.on()
        GPIO_Bin2.off()
        speed = 0.5
        pi.hardware_PWM(GPIO_Apwm, pwm_frequency, dutyHWpwm(speed))
        pi.hardware_PWM(GPIO_Bpwm, pwm_frequency, dutyHWpwm(speed))
        print ("Forward half speed")
        time.sleep(1)

        GPIO_Ain1.on()
        GPIO_Ain2.off()
        GPIO_Bin1.on()
        GPIO_Bin2.off()
        speed = 1
        pi.hardware_PWM(GPIO_Apwm, pwm_frequency, dutyHWpwm(speed))
        pi.hardware_PWM(GPIO_Bpwm, pwm_frequency, dutyHWpwm(speed))
        print ("Forward full speed")
        time.sleep(1)
        
        GPIO_Ain1.off()
        GPIO_Ain2.on()
        GPIO_Bin1.off()
        GPIO_Bin2.on()
        speed = 0.33
        pi.hardware_PWM(GPIO_Apwm, pwm_frequency, dutyHWpwm(speed))
        pi.hardware_PWM(GPIO_Bpwm, pwm_frequency, dutyHWpwm(speed))
        print ("Backward third speed")
        time.sleep(1)

        GPIO_Ain1.off()
        GPIO_Ain2.off()
        GPIO_Bin1.off()
        GPIO_Bin2.off()
        print ("Stop")
        time.sleep(1)

        
# Quit the program when the user presses CTRL + C
except KeyboardInterrupt:
    pass    
finally:
    # Stop the motors
    GPIO_Ain1.off()
    GPIO_Ain2.off()
    GPIO_Bin1.off()
    GPIO_Bin2.off()
    pi.hardware_PWM(GPIO_Apwm, pwm_frequency, 0)
    pi.hardware_PWM(GPIO_Bpwm, pwm_frequency, 0)
    pi.stop()
    # Clean up the resources
    GPIO_Ain1.close()
    GPIO_Ain2.close()
    GPIO_Bin1.close()
    GPIO_Bin2.close()
