# This program demonstrates how to control DC motors connected
# to a motor driver.
# The PWM signal to the motor driver is generated by the
# PCA9685 PWM driver.
# This shows the basic setup without a finite state machine.


# General libraries
import time
# Libraries for the GPIO pins
from gpiozero import OutputDevice
# Libraries for the PWM driver with motors
from adafruit_pca9685 import PCA9685
import busio
import board

 
# Set GPIO Pins (uses BCM numbering)
GPIO_Ain1 = OutputDevice(17)
GPIO_Ain2 = OutputDevice(27)
GPIO_Bin1 = OutputDevice(5)
GPIO_Bin2 = OutputDevice(6)

# Specify the channels you are using on the PWM driver
channel_motor1 = 4
channel_motor2 = 5


# Set the pwm frequency
# However, if we are using ServoKit (for servos),
# this will automatically be overwritten to 50.
pwm_frequency = 1000

# Configure the PWM driver for the motors
i2c = busio.I2C(board.SCL, board.SDA)
pca = PCA9685(i2c)

# Initialize the PWM driver for the motors 
motor_pwmA = pca.channels[channel_motor1]
motor_pwmB = pca.channels[channel_motor2]
pca.frequency = pwm_frequency

# Helper function
def dutyPCA(speed):
    if not 0 <= speed <= 1:
        raise ValueError("Speed must be between 0 and 1")
    return int(speed * 65535)

# Both motors are stopped
GPIO_Ain1.off()
GPIO_Ain2.off()
GPIO_Bin1.off()
GPIO_Bin2.off()

# Set the initial speed of the motors
speed = 0.5
motor_pwmA.duty_cycle = dutyPCA(speed)
motor_pwmB.duty_cycle = dutyPCA(speed)


# Main program
try:
    print("Press CTRL+C to end the program.")
    
    while True:
        
        GPIO_Ain1.on()
        GPIO_Ain2.off()
        GPIO_Bin1.on()
        GPIO_Bin2.off()
        speed = 0.5
        motor_pwmA.duty_cycle = dutyPCA(speed)
        motor_pwmB.duty_cycle = dutyPCA(speed)
        print ("Forward half speed")
        time.sleep(1)

        GPIO_Ain1.on()
        GPIO_Ain2.off()
        GPIO_Bin1.on()
        GPIO_Bin2.off()
        speed = 1.0
        motor_pwmA.duty_cycle = dutyPCA(speed)
        motor_pwmB.duty_cycle = dutyPCA(speed)
        print ("Forward full speed")
        time.sleep(1)

        GPIO_Ain1.off()
        GPIO_Ain2.on()
        GPIO_Bin1.off()
        GPIO_Bin2.on()
        speed = 0.33
        motor_pwmA.duty_cycle = dutyPCA(speed)
        motor_pwmB.duty_cycle = dutyPCA(speed)
        print ("Backward third speed")
        time.sleep(1)

        GPIO_Ain1.off()
        GPIO_Ain2.off()
        GPIO_Bin1.off()
        GPIO_Bin2.off()
        print ("Stop")
        time.sleep(1)


# Quit the program when the user presses CTRL + C
except KeyboardInterrupt:
    pass    
finally:
    # Stop the motors
    GPIO_Ain1.off()
    GPIO_Ain2.off()
    GPIO_Bin1.off()
    GPIO_Bin2.off()
    motor_pwmA.duty_cycle = 0
    motor_pwmB.duty_cycle = 0
    # Clean up the resources
    pca.deinit()
    GPIO_Ain1.close()
    GPIO_Ain2.close()
    GPIO_Bin1.close()
    GPIO_Bin2.close()
    