# This program demonstrates how to control DC motors connected
# to a motor driver.
# The PWM signal to the motor driver is generated by the
# PCA9685 PWM driver.
# This shows the basic setup without a finite state machine.


# General libraries
import time
# Libraries for the GPIO pins
from gpiozero import OutputDevice
# Libraries for the PWM driver with motors
from adafruit_pca9685 import PCA9685
import busio
import board

# Specify the channels you are using on the PWM driver
channel_motor1 = 0
channel_motor2 = 5

pwm_frequency = 1000

# Configure the PWM driver for the motors
i2c = busio.I2C(board.SCL, board.SDA)
pca = PCA9685(i2c)

print(i2c.scan())
pca.frequency = 60
# Initialize the PWM driver for the motors 
motor_pwmA = pca.channels[channel_motor1].duty_cycle = 0x7FFF
motor_pwmB = pca.channels[channel_motor2].duty_cycle = 0x7FFF
pca.frequency = pwm_frequency
